apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pdf-management-system

resources:
  # Namespace (deploy first)
  - namespace.yml
  
  # Secrets and ConfigMaps (deploy second)
  - secret-db.yml
  - configmap-db.yml
  
  # Persistent Volumes and Claims
  - pv-opensearch.yml
  - pv-mysql.yml
  
  # Deployments
  - deployment-mysql.yml
  - deployement-opensearch.yml
  - deployment-backend.yml
  
  # Services
  - service-mysql.yml
  - service-opensearch.yml
  - service-backend.yml

commonLabels:
  app.kubernetes.io/name: pdf-management
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: backend

namespace: chatbot 