apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: chatbot
type: Opaque
data:
  # Base64 encoded values
  # echo -n "12341234" | base64
  mysql-root-password: MTIzNDEyMzQ=
  # echo -n "12341234" | base64
  mysql-password: MTIzNDEyMzQ=
  # echo -n "quhvaR-tygnyz-0tysde" | base64
  opensearch-password:
  # echo -n "AKI6GOZL2F56EF6LP5S" | base64
  aws-access-key-id:
  # echo -n "rfUXlk0ByKGBzWdySUU1Nif4dRjSOlR7U6MVT4He" | base64
  aws-secret-access-key: