apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: chatbot
spec:
  selector:
    app: mysql
  ports:
  - name: "3306"
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP 