apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: chatbot
spec:
  selector:
    app: backend
  ports:
  - name: "8000"
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP 